# Streamlit secrets.toml for deployment
# Add your secrets and config variables here

[general]
email = "muditapachisia@example.com"

[api_keys]
openrouter = "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"
ollama = ""

[other]
# Add other secrets or config variables as needed
